/**
 * The canonical ingredient table (the "bar shelf").
 *
 * The data is GENERATED by the ingestion pipeline (`npm run ingest`) into
 * `data/ingredients.gen.ts` from the validated cocktail catalog, so the shelf
 * always matches exactly the ingredients the catalog uses. This module adds the
 * lookup helpers the app and engine rely on.
 *
 * `contains` drives the constraint engine (diet.ts): ingredients carrying a
 * meaningful amount of alcohol are tagged `alcohol` (bitters are dashes and
 * treated as negligible). dairy/egg tags support the allergen constraints.
 */

import type { Ingredient } from './types';
import { INGREDIENTS } from './data/ingredients.gen';

export { INGREDIENTS };

const BY_SLUG: Map<string, Ingredient> = new Map(INGREDIENTS.map((i) => [i.slug, i]));

export function getIngredient(slug: string): Ingredient | undefined {
  return BY_SLUG.get(slug);
}

export function ingredientName(slug: string): string {
  return BY_SLUG.get(slug)?.name ?? slug;
}

/** True when the ingredient carries a meaningful amount of alcohol. */
export function isAlcoholic(slug: string): boolean {
  return (BY_SLUG.get(slug)?.contains ?? []).includes('alcohol');
}
