/**
 * The full cocktail catalog.
 *
 * The data is GENERATED by the ingestion pipeline (`npm run ingest`) into
 * `data/cocktails.gen.ts` — merged and de-duplicated from our curated set, our
 * Opus+Exa validated research, the IBA official list, and stevana/cocktails,
 * with every ingredient normalized to a canonical slug and every recipe passed
 * through the audit. Re-run `npm run ingest` then `npm run gen:meta` after
 * changing any source.
 */

import type { Cocktail } from '../types';
import { COCKTAILS } from '../data/cocktails.gen';

export { COCKTAILS };

const BY_SLUG: Map<string, Cocktail> = new Map(COCKTAILS.map((c) => [c.slug, c]));

export function getCocktail(slug: string): Cocktail | undefined {
  return BY_SLUG.get(slug);
}

export function allCocktailSlugs(): string[] {
  return COCKTAILS.map((c) => c.slug);
}
