#!/usr/bin/env node
/**
 * generate-sitemap.mjs — post-export step. Writes:
 *   apps/mobile/dist/sitemap.xml   (static routes + every cocktail + every
 *                                   INDEXABLE collection hub)
 *   apps/mobile/dist/robots.txt    (points at the sitemap; disallows /moderate)
 *
 * Host comes from EXPO_PUBLIC_SITE_URL (fallback https://tailsnconk.com).
 * Admin / personal / noindex routes are excluded from the sitemap.
 *
 * Safe by construction: if @tailsnconk/core cannot be loaded, it still emits a
 * sitemap of the static routes so `expo export` never breaks. dist/ is created
 * if the export has not produced it yet.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = fileURLToPath(new URL('.', import.meta.url));
const DIST = join(HERE, '..', 'dist');

const SITE_URL = (process.env.EXPO_PUBLIC_SITE_URL || 'https://tailsnconk.com').replace(/\/$/, '');
const TODAY = new Date().toISOString().slice(0, 10);

/** Public, indexable static routes. NOT /account (personal) or /moderate (admin). */
const STATIC_ROUTES = [
  { path: '/', priority: '1.0', changefreq: 'weekly' },
  { path: '/spin', priority: '0.7', changefreq: 'weekly' },
  { path: '/catalog', priority: '0.9', changefreq: 'weekly' },
  { path: '/collections', priority: '0.8', changefreq: 'weekly' },
  { path: '/about', priority: '0.4', changefreq: 'monthly' },
  { path: '/privacy', priority: '0.2', changefreq: 'yearly' },
  { path: '/terms', priority: '0.2', changefreq: 'yearly' },
];

/** Routes that must never appear in the sitemap (admin/personal/noindex). */
const NOINDEX_ROUTES = ['/moderate', '/account'];

function loc(path) {
  const clean = path === '/' ? '' : path.replace(/\/$/, '');
  return `${SITE_URL}${clean}`;
}

async function loadCore() {
  try {
    const { tsImport } = await import('tsx/esm/api');
    return await tsImport('@tailsnconk/core', import.meta.url);
  } catch (err) {
    console.warn(`generate-sitemap: core unavailable (${err.message}); static routes only.`);
    return null;
  }
}

function xmlUrl({ path, priority = '0.6', changefreq = 'weekly' }) {
  return [
    '  <url>',
    `    <loc>${loc(path)}</loc>`,
    `    <lastmod>${TODAY}</lastmod>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    '  </url>',
  ].join('\n');
}

async function main() {
  const core = await loadCore();

  const routes = [...STATIC_ROUTES];

  if (core) {
    try {
      for (const slug of core.allCocktailSlugs()) {
        routes.push({ path: `/cocktail/${slug}`, priority: '0.8', changefreq: 'monthly' });
      }
      for (const col of core.indexableCollections(core.COCKTAILS)) {
        routes.push({ path: `/collection/${col.slug}`, priority: '0.7', changefreq: 'weekly' });
      }
    } catch (err) {
      console.warn(`generate-sitemap: could not enumerate dynamic routes (${err.message}).`);
    }
  }

  // Guard: never emit a noindex/admin route.
  const filtered = routes.filter((r) => !NOINDEX_ROUTES.some((n) => r.path === n || r.path.startsWith(n + '/')));

  const xml =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    filtered.map(xmlUrl).join('\n') +
    '\n</urlset>\n';

  const robots = [
    '# robots.txt — generated by apps/mobile/scripts/generate-sitemap.mjs',
    'User-agent: *',
    'Allow: /',
    'Disallow: /moderate',
    'Disallow: /account',
    'Disallow: /_sitemap',
    '',
    `Sitemap: ${SITE_URL}/sitemap.xml`,
    '',
  ].join('\n');

  mkdirSync(DIST, { recursive: true });
  writeFileSync(join(DIST, 'sitemap.xml'), xml);
  writeFileSync(join(DIST, 'robots.txt'), robots);

  console.log(`generate-sitemap: wrote ${filtered.length} URL(s) to dist/sitemap.xml and dist/robots.txt (host ${SITE_URL}).`);
}

main().catch((err) => {
  // Never break the export.
  console.error(`generate-sitemap: ${err.message}`);
  process.exit(0);
});
